### PR TITLE
output: add support for sprintf templating in `message_properties`

### PR DESCRIPTION
**Pull request by yaauie**
Several Issues and Pull-Requests have been opened concerning the ability to set a message's `priority` from the content of the message; this PR solves that in such a way that _all_ `message_properties` can support `sprintf` templates without any unnecessary per-event overhead.

1. at plugin registration, properties are split into _constant_ and _variable_ subsets.
2. per event, only the _variable_ properties (if any) are built from the event 

Resolves: #8 
Duplicate of: https://github.com/logstash-plugins/logstash-output-rabbitmq/pull/72
Duplicate of: https://github.com/logstash-plugins/logstash-output-rabbitmq/pull/80

### CODE REVIEW

**Comment by andsel** [comment]
Nice @yaauie I don't know if could be useful to cite this ability also in the documentation.

**Comment by theyough** [comment]
Any update ? When do you plan to release it ?

**Comment by andsel** [comment]
LGTM

**Comment by theyough** [comment]
@yaauie Could you fix conflict, and merge it please ? thank you for your help

**Pull request merged**
